### PR TITLE
Use APFS container instead of HFS

### PR DESCRIPTION
**Pull request by picnicbob**

### CODE REVIEW

**Review by d108 — CHANGES_REQUESTED** [review]
@picnicbob Your adding APFS is appreciated! Instead of removing HFS+, having it as an option would satisfy any use cases where it might be needed/preferred.

Please review the following suggested changes where I've used your code with minor changes. Feel free to improve upon the implementation.

First, I added an enum for the FS types and set a default:

```swift
/// File systems:
enum FileSystemType {
    case apfs
    case hfsPlus
}

/// Constants:
let RAMDISK_GB = 4 // Set the number of gigabytes for the RAM disk here!
let home = NSHomeDirectory()
let derivedDataPath = "\(home)/Library/Developer/Xcode/DerivedData"
let encoding: String.Encoding = .utf8
let fileSystem = FileSystemType.apfs
```

Then switched on the variable during FS creation:

```swift
func makeFilesystemOn(disk: String) throws
{
    var drive = "/dev/rdisk\(disk)"
    var output: String!
    switch fileSystem {
    case .apfs: output = try runTask(launchPath: "/usr/sbin/diskutil",
                                     arguments: ["ap", "createContainer", drive])
        print(output!)
        let apfsMsg = "Disk from APFS operation: "
        let regex = try NSRegularExpression(pattern: "\(apfsMsg)[[:alnum:]]+\n", options: .caseInsensitive)
        var allOutput = NSMakeRange(0, output.count)
        var matchRange = regex.firstMatch(in: output, options: [], range: allOutput)!.range
        drive = String(output[output.index(output.startIndex, offsetBy: (matchRange.location + apfsMsg.count)) ..<
                              output.index(output.startIndex, offsetBy: (matchRange.location + matchRange.length - 1))])
        output = try runTask(launchPath: "/usr/sbin/diskutil",
                             arguments: ["ap", "addVolume", drive, "APFS", "DerivedData", "-nomount"])
        allOutput = NSMakeRange(0, output.count)
        matchRange = regex.firstMatch(in: output, options: [], range: allOutput)!.range
        drive = String(output[output.index(output.startIndex, offsetBy: (matchRange.location + apfsMsg.count)) ..<
                              output.index(output.startIndex, offsetBy: (matchRange.location + matchRange.length - 1))])
    case .hfsPlus: output = try runTask(launchPath: "/sbin/newfs_hfs",
                                        arguments: ["-v", "DerivedData", drive])
    }
    print(output!)
    try mountRamDisk(drive: drive)
}
```

**Comment by picnicbob** [comment]
Good suggestions. I've made the changes and pushed. I can squash those all into one if you'd prefer.

**Comment by d108** [comment]
The code looks good but would prefer that tabs are changed to 4-spaces. One commit is also preferred. Thanks for considering that.

**Comment by picnicbob** [comment]
All set

**Pull request merged**
